#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/var/run/dbus

# delete existing pid if found
[[ -e /var/run/dbus/pid ]] && \
	rm -f /var/run/dbus/pid

# copy config
PREV_DIR=$(pwd)

	cd /usr/local/bin/dvblink/config || exit
	shopt -s globstar nullglob
	for i in *
 	do
	[[ ! -e "/config/${i}" ]] && cp -v "${i}" "/config/${i}"
	done

# permissions
chown messagebus:messagebus \
	/var/run/dbus
dbus-uuidgen --ensure
sleep 1
